### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by soreau** [matijaskala/compiz-earth#3]
I managed to get a crash where es->imagedata[i].image was null when enabling another plugin, so it might be good to conditionally call imageBufferToTexture(), if (es->imagedata[i].image) in earthInitScreen().

**Comment by Eignar17** [comment]
@soreau  is error in new update :/ crash in plugins snow or star and fireflies  conflict in the plugins update plugin @matijaskala

**Comment by Eignar17** [comment]
My compile 
Package compiz-gconf was not found in the pkg-config search path.
Perhaps you should add the directory containing `compiz-gconf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'compiz-gconf' found
convert   : earth.xml.in -> build/earth.xml
bcop'ing  : build/earth.xml -> build/earth_options.h
bcop'ing  : build/earth.xml -> build/earth_options.c
compiling : earth.c -> build/earth.lo
compiling : build/earth_options.c -> build/earth_options.lo
linking   : build/libearth.laar: `u' modifier ignored since `D' is the default (see `U')
linking   : build/libearth.la
Package compiz-gconf was not found in the pkg-config search path.
Perhaps you should add the directory containing `compiz-gconf.pc'
to the PKG_CONFIG_PATH environment variable
No package 'compiz-gconf' found
install   : /home/eignar/.compiz/plugins/libearth.so
install   : /home/eignar/.compiz/metadata/earth.xml
install   : /home/eignar/.compiz/data/earth.vert
install   : /home/eignar/.compiz/data/earth.frag
install   : /home/eignar/.compiz/images/clouds.png
install   : /home/eignar/.compiz/images/day.png
install   : /home/eignar/.compiz/images/night.png
install   : /home/eignar/.compiz/images/skydome.png
